// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: search.proto

/*
Package search is a generated protocol buffer package.

It is generated from these files:
	search.proto

It has these top-level messages:
	SearchQuery
*/
package search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import notes "github.com/mtbarta/monocorpus/pkg/notes"

import (
	context "context"

	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = notes.NoteList{}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Search service

type SearchService interface {
	Search(ctx context.Context, in *SearchQuery, opts ...client.CallOption) (*notes.NoteList, error)
}

type searchService struct {
	c    client.Client
	name string
}

func NewSearchService(name string, c client.Client) SearchService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "search"
	}
	return &searchService{
		c:    c,
		name: name,
	}
}

func (c *searchService) Search(ctx context.Context, in *SearchQuery, opts ...client.CallOption) (*notes.NoteList, error) {
	req := c.c.NewRequest(c.name, "Search.Search", in)
	out := new(notes.NoteList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Search service

type SearchHandler interface {
	Search(context.Context, *SearchQuery, *notes.NoteList) error
}

func RegisterSearchHandler(s server.Server, hdlr SearchHandler, opts ...server.HandlerOption) error {
	type search interface {
		Search(ctx context.Context, in *SearchQuery, out *notes.NoteList) error
	}
	type Search struct {
		search
	}
	h := &searchHandler{hdlr}
	return s.Handle(s.NewHandler(&Search{h}, opts...))
}

type searchHandler struct {
	SearchHandler
}

func (h *searchHandler) Search(ctx context.Context, in *SearchQuery, out *notes.NoteList) error {
	return h.SearchHandler.Search(ctx, in, out)
}
